#To decorate the texts you need to use AdventureAPI MiniMessages! (Wiki: https://docs.advntr.dev/minimessage/index.html)
#To define the materials for crafting, you must follow the updated item pattern! Example: 'LEATHER' 'STONE' 'DIAMOND'.
#To define a backpack when creating, use the special character '$' and in the list of 'items' pass the ID of that backpack as a parameter!

Permission: 'powerfulbackpacks.use' #If this field is not filled in, the permission will be "powerfullbackpacks.use"

Language: 'pt-br'

Backpacks:
  basic_backpack: #ID of Backpack (use sneak_case in the backpack identifier!)
    name: '<grey>Basic Backpack' #Name of Item
    lore: #Lore of Item
      - ''
      - '<grey>Its a Basic Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 1 #Number of Rows
    model_data: 0
    craft: #Craft Struct
      shape: #Shape of Recipe
        - 'LLL'
        - 'L L'
        - 'LLL'
      items: #Items in Recipe
        L: 'LEATHER'
  reinforced_backpack:
    name: '<grey>Reinforced Backpack'
    lore:
      - ''
      - '<grey>Its a Reinforced Backpack'
      - '<grey>Rows: <bold><gold>%backpack_rows%'
      - '<grey>Slots: <bold><gold>%backpack_slots%'
      - ''
    rows: 2
    model_data: 0
    craft:
      shape:
        - 'III'
        - 'I$I'
        - 'III'
      items:
        I: 'IRON_INGOT'
        $: 'basic_backpack'
  ultimate_backpack:
    name: '<gold><bold>Ultimate Backpack'
    lore:
      - ''
      - '<grey>Its a <gold><bold>Ultimate Backpack'
      - ''
      - '<grey>Rows: <gold><bold>%backpack_rows%'
      - '<grey>Slots: <gold><bold>%backpack_slots%'
    rows: 6
    model_data: 0
    craft:
      shape:
        - 'D1D'
        - 'D$D'
        - 'D1D'
      items:
        D: 'DIAMOND'
        $: 'reinforced_backpack'
        1:
          name: '<grey>Custom Item!' #Leave blank if the item don't have a custom name!
          type: 'DIAMOND'
          amount: 1